- name: Example playbook
  hosts: web
  tasks:
    - name: Ping localhost
      ping:

    - name: Instalar Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Iniciar servicio Apache
      service:
        name: apache2
        state: started

    - name: Copiar archivo HTML a la carpeta web
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
